version: '3'

services:
  php:
    build:
      context: ./infrastructure/docker/php-apache/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
  node:
    build:
      context: ./infrastructure/docker/node/
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: all-skate-decks
